# version: '3.9'

services:
  django:
    build:
      context: ./django_project
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  flask:
    build:
      context: ./flask_service
    container_name: flask_service
    command: flask --app flask_service.app --debug run --host=0.0.0.0 --port=5000
    volumes:
      - ./flask_service:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
